"use strict";
const express=require("express");
const billing=require("../../core/billing");
const config={key:"client_invoices",name:"Mis facturas",icon:"ri-file-list-3-line",route:"/invoices",area:"client",category:"Facturación",order:30};
function h(ctx,v){return ctx.layout.escapeHtml(v||"")}
function reg(ctx){return require("../../core/pluginLoader").registry(ctx.db)}
function pill(s){return `<span class="role-pill ${s==='paid'?'user':'admin'}">${s}</span>`}
function printHtml(ctx,inv){const logo=ctx.db.getSetting("site_logo","");const site=ctx.db.getSetting("site_name","SKY ULTRA PLUS shop");const rows=inv.items.map(i=>`<tr><td>${h(ctx,i.name)}<small>${h(ctx,i.description)}</small></td><td>${i.quantity}</td><td>${inv.currency} ${billing.money(i.unit_price)}</td><td>${inv.currency} ${billing.money(i.total)}</td></tr>`).join("");return `<!doctype html><html><head><meta charset="utf-8"><title>${h(ctx,inv.number)}</title><style>body{font-family:Arial;background:#f4f7fb;margin:0;padding:30px;color:#111827}.actions{max-width:900px;margin:auto;text-align:right;padding:0 0 16px}.invoice{max-width:900px;margin:auto;background:white;border-radius:24px;padding:34px;box-shadow:0 24px 70px rgba(15,23,42,.14)}.top{display:flex;justify-content:space-between;border-bottom:2px solid #eef2ff;padding-bottom:20px}.brand{display:flex;gap:14px;align-items:center}.brand img,.fake{width:72px;height:72px;border-radius:18px;object-fit:cover}.fake{display:grid;place-items:center;background:linear-gradient(135deg,#7c3aed,#06b6d4);color:white;font-size:34px;font-weight:900}h1{margin:0;font-size:34px}.pill{display:inline-block;padding:8px 14px;border-radius:999px;background:#dcfce7;color:#166534;font-weight:800}.pending{background:#fef3c7;color:#92400e}.canceled{background:#fee2e2;color:#991b1b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:24px 0}.box{background:#f8fafc;border:1px solid #e5e7eb;border-radius:18px;padding:18px}table{width:100%;border-collapse:collapse}th,td{padding:14px;border-bottom:1px solid #e5e7eb;text-align:left}th{background:#111827;color:white}small{display:block;color:#64748b;margin-top:4px}.total{text-align:right;font-size:28px;font-weight:900;margin-top:22px}@media print{.actions{display:none}body{background:white;padding:0}.invoice{box-shadow:none;border-radius:0}}</style></head><body><div class="actions"><button onclick="window.print()">Descargar / imprimir PDF</button></div><div class="invoice"><div class="top"><div class="brand">${logo?`<img src="${h(ctx,logo)}">`:`<div class="fake">S</div>`}<div><h2>${h(ctx,site)}</h2><p>Factura digital</p></div></div><div><h1>${h(ctx,inv.number)}</h1><span class="pill ${inv.status}">${h(ctx,inv.status).toUpperCase()}</span></div></div><div class="grid"><div class="box"><b>Cliente</b><p>${h(ctx,inv.first_name)} ${h(ctx,inv.last_name)}<br>${h(ctx,inv.email)}<br>${h(ctx,inv.phone||'')}</p></div><div class="box"><b>Fechas</b><p>Creada: ${new Date(inv.created_at).toLocaleString()}<br>Vence: ${inv.due_at?new Date(inv.due_at).toLocaleString():'—'}<br>Pagada: ${inv.paid_at?new Date(inv.paid_at).toLocaleString():'—'}</p></div></div><table><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Total: ${inv.currency} ${billing.money(inv.total)}</div></div></body></html>`}
function detail(ctx,inv,msg=""){const rows=inv.items.map(i=>`<tr><td>${h(ctx,i.name)}<small>${h(ctx,i.description)}</small></td><td>${i.quantity}</td><td>${inv.currency} ${billing.money(i.unit_price)}</td><td>${inv.currency} ${billing.money(i.total)}</td></tr>`).join("");const del=inv.allocations.map(a=>`<div class="delivery-box"><b>Datos del producto</b><textarea readonly>${h(ctx,a.delivered_content)}</textarea></div>`).join("");return `${msg}<div class="card invoice-view"><div class="head-row"><div><p class="eyebrow">Factura</p><h1>${h(ctx,inv.number)}</h1><p>${h(ctx,inv.first_name)} ${h(ctx,inv.last_name)} · ${h(ctx,inv.email)} · ${h(ctx,inv.phone||'')}</p></div><div><h2>${inv.currency} ${billing.money(inv.total)}</h2>${pill(inv.status)}</div></div><div class="form-actions"><a class="btn" href="/invoices/${inv.id}/print" target="_blank">Ver / descargar</a>${inv.status==='pending'?`<form method="POST" action="/invoices/${inv.id}/pay-credit"><button class="btn">Pagar con crédito</button></form>`:""}</div><table><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><h2 class="invoice-total">Total: ${inv.currency} ${billing.money(inv.total)}</h2>${del}</div>`}
function router(ctx){const r=express.Router();
 r.post("/:id/pay-credit",(req,res)=>{const out=billing.payWithCredits(ctx.db,req.params.id,req.session.user.id);res.redirect(out.ok?`/invoices/${req.params.id}?paid=1`:`/invoices/${req.params.id}?error=${encodeURIComponent(out.error)}`)});
 r.get("/:id/print",(req,res)=>{const inv=billing.fullInvoice(ctx.db,req.params.id);if(!inv||Number(inv.user_id)!==Number(req.session.user.id))return res.status(404).send("Factura no encontrada");res.send(printHtml(ctx,inv))});
 r.get("/:id",(req,res)=>{const inv=billing.fullInvoice(ctx.db,req.params.id);if(!inv||Number(inv.user_id)!==Number(req.session.user.id))return res.redirect('/invoices');const msg=req.query.error?`<div class="notice error">${h(ctx,req.query.error)}</div>`:req.query.paid?`<div class="notice success">Factura pagada.</div>`:"";res.renderPage({title:inv.number,area:"client",registry:reg(ctx),content:detail(ctx,inv,msg)})});
 r.get("/",(req,res)=>{const inv=ctx.db.sqlite.prepare("SELECT * FROM invoices WHERE user_id=? ORDER BY id DESC").all(req.session.user.id);const rows=inv.map(i=>`<tr><td><a href="/invoices/${i.id}">${h(ctx,i.number)}</a></td><td>${h(ctx,i.type)}</td><td>${pill(i.status)}</td><td>${i.currency} ${billing.money(i.total)}</td><td>${new Date(i.created_at).toLocaleString()}</td><td><a href="/invoices/${i.id}">Ver</a></td></tr>`).join("");res.renderPage({title:"Mis facturas",area:"client",registry:reg(ctx),content:`<div class="page-head"><h1>Mis facturas</h1><p>Consulta tus facturas, pagos y productos comprados.</p></div><div class="card table-card"><table><thead><tr><th>Número</th><th>Tipo</th><th>Estado</th><th>Total</th><th>Fecha</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="6">No tienes facturas todavía.</td></tr>'}</tbody></table></div>`})});
 return r}
module.exports={config,router,detail,printHtml};
