"use strict";
const express=require("express");
const billing=require("../../core/billing");
const config={key:"client_products",name:"Productos",icon:"ri-shopping-bag-3-line",route:"/products",area:"client",category:"Tienda",order:10};
function h(ctx,v){return ctx.layout.escapeHtml(v||"")}
function reg(ctx){return require("../../core/pluginLoader").registry(ctx.db)}
function stock(ctx,id){return ctx.db.sqlite.prepare("SELECT COUNT(*) c FROM product_inventory_items WHERE product_id=? AND status='available'").get(id).c||0}
function cycle(p){if(p.billing_type==="one_time")return"Pago único";if(Number(p.cycle_minutes)>0)return`Cada ${p.cycle_minutes} min`;return`Cada ${p.cycle_days||30} días`}
function router(ctx){const r=express.Router();
 r.post("/:id/buy-credit",(req,res)=>{const out=billing.buyWithCredits(ctx.db,req.session.user.id,req.params.id);res.redirect(out.ok?`/services?bought=1`:`/products?error=${encodeURIComponent(out.error)}`)});
 r.get("/",(req,res)=>{const err=req.query.error?`<div class="notice error">${h(ctx,req.query.error)}</div>`:"";const cats=ctx.db.sqlite.prepare("SELECT * FROM product_categories WHERE active=1 ORDER BY order_index,id").all();let html=`<div class="page-head"><h1>Productos</h1><p>Compra productos digitales con tus créditos disponibles.</p></div>${err}`;for(const c of cats){const ps=ctx.db.sqlite.prepare("SELECT * FROM products WHERE active=1 AND category_id=? ORDER BY id DESC").all(c.id);if(!ps.length)continue;html+=`<div class="store-category-head" id="cat-${c.id}">${c.image_path?`<img src="${h(ctx,c.image_path)}">`:`<i class="${h(ctx,c.icon||'ri-price-tag-3-line')}"></i>`}<div><h2>${h(ctx,c.name)}</h2><p>${h(ctx,c.description||"")}</p></div></div><div class="grid cards-3">`;for(const p of ps){const s=stock(ctx,p.id);const w=ctx.db.getWallet(req.session.user.id,p.currency);const enough=Number(w.balance)>=Number(p.price);html+=`<div class="card product-card">${p.image_path?`<img class="product-img" src="${h(ctx,p.image_path)}">`:""}<h3>${h(ctx,p.name)}</h3><p>${h(ctx,p.description)}</p><div class="product-meta"><span>${p.currency} ${billing.money(p.price)}</span><span>${cycle(p)}</span><span>Stock ${s}</span><span>Tu crédito ${p.currency} ${billing.money(w.balance)}</span></div><form method="POST" action="/products/${p.id}/buy-credit"><button class="btn" ${s<=0||!enough?"disabled":""}>Comprar con crédito</button></form>${!enough?`<small>Crédito insuficiente.</small>`:""}</div>`}html+=`</div>`}if(!cats.length)html+=`<div class="card">No hay productos disponibles.</div>`;res.renderPage({title:"Productos",area:"client",registry:reg(ctx),content:html})});
 return r}
module.exports={config,router};
