"use strict";
const express=require("express");
const billing=require("../../core/billing");
const config={key:"client_services",name:"Mis servicios",icon:"ri-archive-stack-line",route:"/services",area:"client",category:"Cuenta",order:20};
function h(ctx,v){return ctx.layout.escapeHtml(v||"")}
function reg(ctx){return require("../../core/pluginLoader").registry(ctx.db)}
function router(ctx){const r=express.Router();
r.post("/:id/cancel",(req,res)=>{billing.cancelService(ctx.db,req.params.id,req.session.user.id);res.redirect("/services?canceled=1")});
r.get("/",(req,res)=>{const list=ctx.db.sqlite.prepare("SELECT s.*,p.name,p.description,p.image_path,i.number invoice_number FROM services s JOIN products p ON p.id=s.product_id LEFT JOIN invoices i ON i.id=s.invoice_id WHERE s.user_id=? ORDER BY s.id DESC").all(req.session.user.id);let cards="";for(const s of list){const a=s.status==='active'?ctx.db.sqlite.prepare("SELECT delivered_content FROM delivery_allocations WHERE invoice_id=? AND user_id=? LIMIT 1").get(s.invoice_id,req.session.user.id):null;cards+=`<div class="card product-card ${s.status==='canceled'?'is-canceled':''}"><div class="product-meta"><span>Servicio #${s.id}</span><span>${h(ctx,s.status)}</span></div>${s.image_path?`<img class="product-img" src="${h(ctx,s.image_path)}">`:""}<h3>${h(ctx,s.name)}</h3><p>${h(ctx,s.description)}</p><div class="product-meta"><span>Factura ${h(ctx,s.invoice_number||'—')}</span><span>${s.next_invoice_at?new Date(s.next_invoice_at).toLocaleString():'Sin renovación'}</span></div>${s.status!=='active'?'<div class="notice error">Servicio cancelado. La información privada está oculta.</div>':''}${a?`<div class="delivery-box"><b>Información del producto</b><textarea readonly>${h(ctx,a.delivered_content)}</textarea></div>`:""}<div class="form-actions"><a class="btn ghost" href="/invoices/${s.invoice_id}">Ver factura</a>${s.status==='active'?`<form method="POST" action="/services/${s.id}/cancel" onsubmit="return confirm('¿Seguro que quieres cancelar este servicio? La información privada quedará oculta.')"><button class="btn danger">Cancelar servicio</button></form>`:""}</div></div>`}const msg=req.query.bought?'<div class="notice success">Compra completada.</div>':req.query.canceled?'<div class="notice success">Servicio cancelado.</div>':'';res.renderPage({title:"Mis servicios",area:"client",registry:reg(ctx),content:`<div class="page-head"><h1>Mis servicios</h1><p>Los servicios cancelados se conservan como historial, pero no muestran la información privada.</p></div>${msg}<div class="grid cards-3">${cards||'<div class="card">No tienes servicios todavía.</div>'}</div>`})});return r}
module.exports={config,router};
